qlib_init:
    provider_uri: "~/igorlima/igor_tcc/qlib_data/br_data"
    region: us
market: &market ibov
benchmark: &benchmark ^bvsp

data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2022-02-24
    fit_start_time: 2008-01-01
    fit_end_time: 2017-12-31
    instruments: *market
    infer_processors: 
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2020-01-01
        end_time: 2022-02-24
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: DNNModelPytorch
        module_path: qlib.contrib.model.pytorch_nn
        kwargs:
            loss: mse
            optimizer: gd
            batch_size: 8192
            lr: 0.005652319068993379
            max_steps: 6000
            eval_train_metric: true
            tensorboard: true
            tensorboard_name: "gd_test_number_126"
            GPU: 0
            pt_model_kwargs:
              input_dim: 360
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha360
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2017-12-31]
                valid: [2018-01-01, 2019-12-31]
                test: [2020-01-01, 2022-02-24]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
